In [1]:
import numpy as np

a = np.array([2,3,4,5])

In [3]:
a

array([2, 3, 4, 5])

In [4]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.arange(10,20)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
c = np.arange(10,20,2)
c

array([10, 12, 14, 16, 18])

In [12]:
d = np.array([2,3,300],dtype = np.int16)
d

array([  2,   3, 300], dtype=int16)

**Linspace method**

In [14]:
e = np.linspace(3,10,20)
e

array([ 3.        ,  3.36842105,  3.73684211,  4.10526316,  4.47368421,
        4.84210526,  5.21052632,  5.57894737,  5.94736842,  6.31578947,
        6.68421053,  7.05263158,  7.42105263,  7.78947368,  8.15789474,
        8.52631579,  8.89473684,  9.26315789,  9.63157895, 10.        ])

**Attribute-->shape,dimension**

In [15]:
a.ndim

1

In [16]:
a.shape

(4,)

**2-D array**

In [18]:
a = np.array([[2,5,4],
             [6,7,8]])
a

array([[2, 5, 4],
       [6, 7, 8]])

In [19]:
a.ndim

2

In [20]:
a.shape

(2, 3)

**ones method-->for creating 2D aaray**

In [2]:
a = np.ones([3,5])
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**zeros method**

In [3]:
a = np.zeros([3,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**eye method**

In [10]:
b = np.eye(4)  #also known identity matrix
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**diag**

In [5]:
d = np.diag([1,4,6])
d

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

In [6]:
np.diag(d)

array([1, 4, 6])

**rand method**

In [12]:
r = np.random.rand(5)
r

array([0.96849015, 0.6118597 , 0.56035458, 0.71724789, 0.33585902])

In [13]:
r = np.random.randn(6)
r

array([-0.43177843,  1.40651296, -0.0262812 , -2.04081935, -1.91761489,
       -0.89822608])

**Complex array**

In [16]:
c = np.array([2+4j , 5+7j])
c.dtype

dtype('complex128')

**Boolean array**

In [18]:
b = np.array([[True,False],
             [False,False]])
b.dtype

dtype('bool')

**View**

In [2]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b = v[::2]
b[2]=0
b
v

array([0, 1, 2, 3, 0, 5, 6, 7, 8, 9])

**copy()**

In [9]:
c = v[::2].copy()
c[2]=4
c
v

array([0, 2, 4, 6, 8])

**Boolean indexing (fancy indexing)**

In [15]:
#to filter all odd nos.
a = np.arange(20)
mask = (a % 2 != 0)
a[mask]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

**Basic Operations**

In [2]:
a = np.array([1,2,3,4])
a+1


array([2, 3, 4, 5])

In [9]:
b = np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [11]:
np.log(a)
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [14]:
#operation on 2D array

a = np.array([[2,3,4],[5,6,7],[3,5,7]])
a

array([[2, 3, 4],
       [5, 6, 7],
       [3, 5, 7]])

In [15]:
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
a*b

array([[2., 0., 0.],
       [0., 6., 0.],
       [0., 0., 7.]])

**Dot Product**

In [3]:
c = np.array([1,2,3])
d = np.array([4,5,6])
c.dot(d)

32

In [5]:
a = np.array([[2,4,5],
            [4,7,8]])
np.sum(a, axis=0)
np.sum(a, axis=1)

array([11, 19])

In [2]:
a = np.array([True,False,True,True])
np.any(a)  #returns true if passed argument has true in it

True

In [3]:
np.all(a)  #returns true if all arguments passed are true 

False

In [5]:
b = np.array([1,4,5])
b>0
np.all(b)

True

**x<y<z**

In [6]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])

In [7]:
res1 = x<y
res1

array([ True,  True,  True])

In [8]:
res2 = y<z
res2

array([ True,  True,  True])

In [9]:
res3 = res1 & res2
res3

array([ True,  True,  True])

In [10]:
np.all(res3)

True

**Tile Function--> construct a new array by repeating array**

In [5]:
t = np.array([1,2,3])
b = np.tile(t,2)
b

array([1, 2, 3, 1, 2, 3])

In [5]:
a = np.array([1,2,3])
b = a[0:3, np.newaxis]
b

array([[1],
       [2],
       [3]])

**Broadcasting**

In [13]:
#type 1

a = np.array([[4,5,6],[7,8,9],[1,2,3]])
a


array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [ ]:
b = np.array([1,2,3])

In [9]:
c = a+b #rows in a will repeate
c

array([[ 5,  7,  9],
       [ 8, 10, 12]])

In [10]:
#type 2
#col will repeat

d = np.array([[1],[0],[1]])
d

array([[1],
       [0],
       [1]])

In [14]:
e = a+d
e

array([[5, 6, 7],
       [7, 8, 9],
       [2, 3, 4]])

In [15]:
#type 3

f = np.array([1,1,0])
g = np.array([[1],[2],[1]])

In [16]:
h = f+g
h

array([[2, 2, 1],
       [3, 3, 2],
       [2, 2, 1]])

**Flattening array**

In [18]:
f = np.array([[1,2,3],[4,5,6]])
np.ravel(f)

array([1, 2, 3, 4, 5, 6])

**Reshape array**

In [22]:
a = np.array([[1,2,3],[4,5,6]])
a
np.reshape(a,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
b = np.arange(18).reshape(2,3,3)  #product needs to be 18 here, as there are 18 elements
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [29]:
#sorting 1D array

s = np.random.randint(1,10,6)
s = np.sort(s)
s

array([2, 4, 4, 5, 6, 7])

In [31]:
s = s[::-1]  #descending order
s

array([7, 6, 5, 4, 4, 2])

**2D array sorting**

In [37]:
x = np.array([[1,5,2],
              [6,3,8]])
np.sort(x,axis=0)

array([[1, 3, 2],
       [6, 5, 8]])

In [34]:
np.sort(x,axis=1)

array([[1, 2, 5],
       [3, 6, 8]])

In [6]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [10]:
np.vstack([np.repeat(a,3),np.tile(a,3)])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [11]:
np.empty([3,3])

array([[4.9e-324, 4.9e-324, 4.9e-324],
       [9.9e-324, 9.9e-324, 9.9e-324],
       [1.5e-323, 1.5e-323, 1.5e-323]])